# Домашнее задание: Степенной метод нахождения собственных значений и собственных векторов

## Теория

### Собственные значения и собственные векторы

Для квадратной матрицы $A$ размера $n \times n$ число $\lambda$ называется **собственным значением**, а ненулевой вектор $\mathbf{v}$ — **собственным вектором**, если:

$$A\mathbf{v} = \lambda \mathbf{v}$$

### Степенной метод

Степенной метод находит **доминирующее собственное значение** (наибольшее по модулю) и соответствующий собственный вектор.

**Алгоритм:**
1. Выбрать начальный вектор $\mathbf{x}^{(0)}$
2. Итеративно вычислять:
   - $\mathbf{y}^{(k)} = A\mathbf{x}^{(k-1)}$
   - $\mathbf{x}^{(k)} = \mathbf{y}^{(k)} / \|\mathbf{y}^{(k)}\|$
   - $\lambda^{(k)} = (\mathbf{x}^{(k)})^T A \mathbf{x}^{(k)}$ (отношение Рэлея)
3. Повторять до сходимости

### Нахождение второго собственного значения (метод дефляции)

После нахождения первого собственного значения $\lambda_1$ и вектора $\mathbf{v}_1$, можно построить матрицу:

$$A_2 = A - \lambda_1 \mathbf{v}_1 \mathbf{v}_1^T$$

Применив степенной метод к $A_2$, найдём второе собственное значение.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

## Задание 1: Реализация степенного метода

Реализуйте степенной метод для нахождения доминирующего собственного значения и соответствующего собственного вектора.

In [2]:
def power_method(A, tol=1e-10, max_iter=1000):
    """
    Степенной метод для нахождения доминирующего собственного значения и вектора.

    Параметры:
        A: квадратная матрица
        tol: допустимая погрешность для критерия сходимости
        max_iter: максимальное число итераций

    Возвращает:
        eigenvalue: доминирующее собственное значение
        x: соответствующий собственный вектор (нормированный)
    """
    n = A.shape[0]

    # TODO: Инициализируйте случайный начальный вектор x размера n
    # и нормируйте его (разделите на его норму)
    x = np.random.rand(n)
    x = x / np.linalg.norm(x)

    eigenvalue_old = 0

    for i in range(max_iter):
        # TODO: Умножьте матрицу A на вектор x
        y = A @ x

        # TODO: Вычислите отношение Рэлея для оценки собственного значения
        # eigenvalue = x^T @ y (скалярное произведение x и y)
        eigenvalue = x.T @ y

        # TODO: Нормируйте вектор y (разделите на его норму)
        x = y / np.linalg.norm(y)

        # Проверка сходимости
        if abs(eigenvalue - eigenvalue_old) < tol:
            print(f"Сходимость за {i+1} итераций")
            break
        eigenvalue_old = eigenvalue

    return eigenvalue, x

## Пример: матрица 5x5

Создадим симметричную матрицу и найдём два первых собственных значения и вектора.

In [3]:
# Создаём симметричную матрицу 5x5
np.random.seed(42)
B = np.random.rand(5, 5)
A = B @ B.T + np.eye(5)  # Симметричная, положительно определённая

print("Матрица A:")
print(A)

Матрица A:
[[2.962687 1.218018 1.694647 1.046083 0.866111]
 [1.218018 2.640675 1.036974 0.966673 0.899753]
 [1.694647 1.036974 2.712258 0.880364 0.551803]
 [1.046083 0.966673 0.880364 1.672961 0.59903 ]
 [0.866111 0.899753 0.551803 0.59903  1.821392]]


In [4]:
# Находим первое (максимальное) собственное значение
lambda1, v1 = power_method(A)

print(f"\nПервое собственное значение: {lambda1:.10f}")
print(f"Первый собственный вектор: {v1}")

Сходимость за 12 итераций

Первое собственное значение: 6.5296998592
Первый собственный вектор: [0.570228 0.466272 0.501785 0.343149 0.296466]


## Задание 2: Метод дефляции

Используйте метод дефляции для нахождения второго собственного значения.

In [5]:
# TODO: Примените метод дефляции: вычтите вклад первого собственного значения
# A2 = A - lambda1 * v1 @ v1^T
# Используйте np.outer(v1, v1) для вычисления внешнего произведения v1 @ v1^T
A2 = A - lambda1 * np.outer(v1, v1)

# Находим второе собственное значение
lambda2, v2 = power_method(A2)

print(f"\nВторое собственное значение: {lambda2:.10f}")
print(f"Второй собственный вектор: {v2}")

Сходимость за 33 итераций

Второе собственное значение: 1.9176068559
Второй собственный вектор: [-0.334036  0.615169 -0.543964  0.131312  0.443675]


## Задание 3: Проверка результатов

Сравните полученные результаты с numpy и проверьте корректность.

In [6]:
# Проверка с numpy
eigenvalues_np, eigenvectors_np = np.linalg.eigh(A)  # eigh для симметричных матриц

print("=" * 50)
print("Проверка с numpy:")
print("=" * 50)
print(f"Все собственные значения (по убыванию): {eigenvalues_np[::-1]}")
print(f"\nНаши результаты:")
print(f"  lambda_1 = {lambda1:.6f} (numpy: {eigenvalues_np[-1]:.6f})")
print(f"  lambda_2 = {lambda2:.6f} (numpy: {eigenvalues_np[-2]:.6f})")

Проверка с numpy:
Все собственные значения (по убыванию): [6.5297   1.917607 1.309879 1.052787 1.      ]

Наши результаты:
  lambda_1 = 6.529700 (numpy: 6.529700)
  lambda_2 = 1.917607 (numpy: 1.917607)


In [7]:
# TODO: Проверьте, что A*v = lambda*v для найденных собственных значений и векторов
# Вычислите норму разности ||A*v1 - lambda1*v1|| и ||A*v2 - lambda2*v2||

print("\nПроверка A*v = lambda*v:")

# TODO: Вычислите норму ||A @ v1 - lambda1 * v1||
error1 = np.linalg.norm(A @ v1 - lambda1 * v1)
print(f"||A*v1 - lambda1*v1|| = {error1:.2e}")

# TODO: Вычислите норму ||A @ v2 - lambda2 * v2||
error2 = np.linalg.norm(A @ v2 - lambda2 * v2)
print(f"||A*v2 - lambda2*v2|| = {error2:.2e}")


Проверка A*v = lambda*v:
||A*v1 - lambda1*v1|| = 5.99e-07
||A*v2 - lambda2*v2|| = 4.21e-06


## Задание 4: Проверка ортогональности

Для симметричной матрицы собственные векторы, соответствующие разным собственным значениям, должны быть ортогональны.

In [8]:
# TODO: Проверьте ортогональность v1 и v2
# Вычислите скалярное произведение v1 @ v2 (должно быть близко к 0)
dot_product = v1 @ v2
print(f"\nОртогональность v1 и v2: v1·v2 = {abs(dot_product):.2e}")


Ортогональность v1 и v2: v1·v2 = 3.13e-07


## Задание 5 (дополнительное): Нахождение третьего собственного значения

Примените метод дефляции ещё раз, чтобы найти третье собственное значение.

In [9]:
# TODO: Примените метод дефляции к A2, чтобы найти третье собственное значение
# A3 = A2 - lambda2 * v2 @ v2^T
A3 = A2 - lambda2 * np.outer(v2, v2)

lambda3, v3 = power_method(A3)

print(f"\nТретье собственное значение: {lambda3:.10f}")
print(f"Третий собственный вектор: {v3}")
print(f"\nСравнение с numpy: {eigenvalues_np[-3]:.6f}")

Сходимость за 50 итераций

Третье собственное значение: 1.3098790012
Третий собственный вектор: [ 0.390365 -0.541836 -0.311679 -0.039645  0.674769]

Сравнение с numpy: 1.309879


## Итоги

В этом задании вы:
1. Реализовали степенной метод для нахождения доминирующего собственного значения
2. Применили метод дефляции для нахождения последующих собственных значений
3. Проверили корректность результатов сравнением с numpy
4. Убедились в ортогональности собственных векторов симметричной матрицы